"use client";

import { useEffect } from "react";
import { initSPWorlds } from "@/lib/spworlds";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    initSPWorlds();
  }, []);

  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="frame-ancestors https://spworlds.ru;"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
